### ISSUE TITLE
SourceCommand does not implement damage.Source (missing Fire method)

### ISSUE THREAD

**Issue by tristanmorgan** [AndreasHGK/df-commands#1]
Hi @AndreasHGK,
I was trying to compile with latest dragonfly and the /kill command needs a code snippet added.

```
func (SourceCommand) Fire() bool { return false }
```

**Comment by andreashgk** [comment]
Thank you for reporting, this should be fixed with the latest commit!

**Comment by tristanmorgan** [comment]
Thanks.
